const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const REGISTRY = process.env.REGISTRY || "localhost:5000";

// Folders we look for in the repo, in priority order
const KNOWN_OUTPUT_DIRS = ["dist", "build", "out", "public", ".next"];

/**
 * Scans the cloned repo for a known static output directory.
 *
 * @param {string} repoPath - Absolute path to the cloned repo
 * @returns {string}        - Name of the output directory (e.g. "dist")
 * @throws                  - If no known output directory is found
 */
function detectOutputDir(repoPath) {
  for (const dir of KNOWN_OUTPUT_DIRS) {
    if (fs.existsSync(path.join(repoPath, dir))) {
      return dir;
    }
  }

  throw new Error(
    `No output directory found in repo. Expected one of: ${KNOWN_OUTPUT_DIRS.join(", ")}. ` +
    `Ensure your site is pre-built and the output folder is committed.`
  );
}

/**
 * Writes a minimal Dockerfile into the repo directory.
 * Uses a plain nginx:alpine image and copies the output folder into it.
 *
 * @param {string} repoPath   - Absolute path to the cloned repo
 * @param {string} outputDir  - Detected output directory (e.g. "dist")
 */
function generateDockerfile(repoPath, outputDir) {
  const nginxConfSrc = path.join(__dirname, "../templates/nginx.conf");
  const nginxConfDst = path.join(repoPath, "nginx.conf");

  // Copy our nginx config into the repo so Dockerfile can reference it
  fs.copyFileSync(nginxConfSrc, nginxConfDst);

  const dockerfile = `
# Auto-generated by deploy-platform
FROM nginx:alpine

# Remove default nginx static content
RUN rm -rf /usr/share/nginx/html/*

# Copy pre-built static files
COPY ${outputDir}/ /usr/share/nginx/html/

# Copy our nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
`.trimStart();

  fs.writeFileSync(path.join(repoPath, "Dockerfile"), dockerfile, "utf8");
}

/**
 * Builds the Docker image from the repo directory and pushes it to the local registry.
 * Returns the full image tag so Kubernetes knows what to pull.
 *
 * @param {string} repoPath - Absolute path to the cloned repo
 * @param {string} slug     - Deployment slug, used as image name
 * @param {object} logger   - Deployment logger instance
 * @returns {string}        - Full image tag e.g. "localhost:5000/my-site:latest"
 */
function buildAndPushImage(repoPath, slug, logger) {
  const imageTag = `${REGISTRY}/${slug}:latest`;

  logger.step(`Detecting output directory...`);
  const outputDir = detectOutputDir(repoPath);
  logger.info(`Found output directory: ${outputDir}/`);

  logger.step(`Generating Dockerfile (output: ${outputDir}/)...`);
  generateDockerfile(repoPath, outputDir);
  logger.info(`Dockerfile written`);

  logger.step(`Building Docker image: ${imageTag}`);
  execSync(`docker build -t ${imageTag} ${repoPath}`, {
    stdio: "pipe",
    timeout: 120_000, // 2 min max for docker build
  });
  logger.info(`Image built successfully`);

  logger.step(`Pushing image to registry: ${REGISTRY}`);
  execSync(`docker push ${imageTag}`, {
    stdio: "pipe",
    timeout: 60_000,
  });
  logger.info(`Image pushed: ${imageTag}`);

  return imageTag;
}

module.exports = { buildAndPushImage, detectOutputDir };
