const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const MANIFESTS_DIR = process.env.MANIFESTS_DIR || "/opt/deploy-platform/manifests";
const NGINX_SITES_DIR = process.env.NGINX_SITES_DIR || "/etc/nginx/deploy-platform";
const MINIKUBE_IP = process.env.MINIKUBE_IP || execSync("minikube ip").toString().trim();

if (!fs.existsSync(MANIFESTS_DIR)) {
  fs.mkdirSync(MANIFESTS_DIR, { recursive: true });
}

/**
 * Generates a Kubernetes manifest (Deployment + Service + Ingress) for a site.
 */
function generateManifest(slug, imageTag) {
  return `
# Auto-generated by deploy-platform for slug: ${slug}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-${slug}
  namespace: default
  labels:
    app: site-${slug}
    managed-by: deploy-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-${slug}
  template:
    metadata:
      labels:
        app: site-${slug}
    spec:
      containers:
        - name: site
          image: ${imageTag}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-${slug}
  namespace: default
  labels:
    managed-by: deploy-platform
spec:
  selector:
    app: site-${slug}
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-${slug}
  namespace: default
  labels:
    managed-by: deploy-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ${slug}.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-${slug}
                port:
                  number: 80
`.trimStart();
}

/**
 * Generates a host nginx server block for this slug.
 * Listens for requests with Host: <slug>.localhost and proxies them
 * into the minikube ingress controller which handles the rest.
 *
 * Traffic flow:
 *   LAN machine → host nginx (port 80) → minikube ingress → pod
 */
function generateNginxConfig(slug) {
  return `
# Auto-generated by deploy-platform for slug: ${slug}
# To remove this site: DELETE /deploy/${slug}
server {
    listen 80;
    server_name ${slug}.localhost;

    location / {
        proxy_pass http://${MINIKUBE_IP};
        proxy_set_header Host ${slug}.localhost;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 10s;
        proxy_read_timeout 30s;
    }
}
`.trimStart();
}

/**
 * Writes the nginx config for a slug and reloads nginx so it takes effect immediately.
 * The NGINX_SITES_DIR is owned by the current user (set up by setup-server.sh)
 * so no sudo is needed to write the file.
 */
function applyNginxConfig(slug, logger) {
  const configPath = path.join(NGINX_SITES_DIR, `${slug}.conf`);
  const config = generateNginxConfig(slug);

  logger.step(`Writing host nginx config → ${configPath}`);
  fs.writeFileSync(configPath, config, "utf8");

  logger.step(`Reloading host nginx...`);
  execSync("sudo nginx -t && sudo systemctl reload nginx", {
    stdio: "pipe",
    timeout: 10_000,
  });

  logger.info(`Host nginx reloaded — site routable on LAN`);
}

/**
 * Applies the k8s manifest and then writes + reloads the host nginx config.
 * After this function returns, the site is accessible from anywhere on the LAN
 * as long as the client has <slug>.localhost pointing to this server's LAN IP.
 */
function applyManifest(slug, imageTag, logger) {
  // ── Kubernetes ──────────────────────────────────────────────────────────────
  const manifestPath = path.join(MANIFESTS_DIR, `${slug}.yaml`);
  const manifest = generateManifest(slug, imageTag);

  logger.step(`Writing Kubernetes manifest → ${manifestPath}`);
  fs.writeFileSync(manifestPath, manifest, "utf8");

  logger.step(`Applying manifest to cluster (kubectl apply)...`);
  execSync(`kubectl apply -f ${manifestPath}`, {
    stdio: "pipe",
    timeout: 30_000,
  });
  logger.info(`Manifest applied`);

  logger.step(`Waiting for rollout: site-${slug}...`);
  execSync(
    `kubectl rollout status deployment/site-${slug} --namespace=default --timeout=90s`,
    { stdio: "pipe", timeout: 95_000 }
  );
  logger.info(`Rollout complete`);

  // ── Host nginx ──────────────────────────────────────────────────────────────
  applyNginxConfig(slug, logger);
}

/**
 * Tears down everything for a slug:
 *  - deletes the k8s resources
 *  - removes the host nginx config and reloads
 */
function deleteDeployment(slug, logger) {
  const manifestPath = path.join(MANIFESTS_DIR, `${slug}.yaml`);
  const nginxConfigPath = path.join(NGINX_SITES_DIR, `${slug}.conf`);

  if (fs.existsSync(manifestPath)) {
    logger.step(`Deleting Kubernetes resources for ${slug}...`);
    execSync(`kubectl delete -f ${manifestPath} --ignore-not-found=true`, {
      stdio: "pipe",
      timeout: 30_000,
    });
    fs.unlinkSync(manifestPath);
    logger.info(`Kubernetes resources deleted`);
  }

  if (fs.existsSync(nginxConfigPath)) {
    logger.step(`Removing host nginx config for ${slug}...`);
    fs.unlinkSync(nginxConfigPath);
    execSync("sudo nginx -t && sudo systemctl reload nginx", {
      stdio: "pipe",
      timeout: 10_000,
    });
    logger.info(`Host nginx config removed and reloaded`);
  }
}

module.exports = { applyManifest, generateManifest, deleteDeployment };