const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const MANIFESTS_DIR = process.env.MANIFESTS_DIR || "/opt/deploy-platform/manifests";
const NGINX_SITES_DIR = process.env.NGINX_SITES_DIR || "/etc/nginx/deploy-platform";
const MINIKUBE_IP = process.env.MINIKUBE_IP || execSync("minikube ip").toString().trim();
const BASE_DOMAIN = process.env.BASE_DOMAIN || "siteportal.web";

if (!fs.existsSync(MANIFESTS_DIR)) {
  fs.mkdirSync(MANIFESTS_DIR, { recursive: true });
}

/**
 * Returns the full public hostname for a slug.
 * e.g. "testing" → "testing.siteportal.web"
 */
function getHostname(slug) {
  return `${slug}.${BASE_DOMAIN}`;
}

/**
 * Generates a Kubernetes manifest (Deployment + Service + Ingress) for a site.
 */
function generateManifest(slug, imageTag) {
  const hostname = getHostname(slug);

  return `
# Auto-generated by deploy-platform
# Site: ${hostname}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-${slug}
  namespace: default
  labels:
    app: site-${slug}
    managed-by: deploy-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-${slug}
  template:
    metadata:
      labels:
        app: site-${slug}
    spec:
      containers:
        - name: site
          image: ${imageTag}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-${slug}
  namespace: default
  labels:
    managed-by: deploy-platform
spec:
  selector:
    app: site-${slug}
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-${slug}
  namespace: default
  labels:
    managed-by: deploy-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ${hostname}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-${slug}
                port:
                  number: 80
`.trimStart();
}

/**
 * Generates the host nginx server block for a slug.
 * Listens for <slug>.siteportal.web and proxies into minikube ingress.
 *
 * Traffic flow:
 *   LAN browser → host nginx (10.10.x.x:80) → minikube ingress (192.168.49.2) → pod
 */
function generateNginxConfig(slug) {
  const hostname = getHostname(slug);

  return `
# Auto-generated by deploy-platform for: ${hostname}
server {
    listen 80;
    server_name ${hostname};

    location / {
        proxy_pass         http://${MINIKUBE_IP};
        proxy_set_header   Host              ${hostname};
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_connect_timeout 10s;
        proxy_read_timeout    30s;
    }
}
`.trimStart();
}

/**
 * Writes the host nginx config for a slug and reloads nginx.
 */
function applyNginxConfig(slug, logger) {
  const configPath = path.join(NGINX_SITES_DIR, `${slug}.conf`);

  logger.step(`Writing host nginx config → ${configPath}`);
  fs.writeFileSync(configPath, generateNginxConfig(slug), "utf8");

  logger.step(`Reloading host nginx...`);
  execSync("sudo nginx -t && sudo systemctl reload nginx", {
    stdio: "pipe",
    timeout: 10_000,
  });

  logger.info(`Nginx reloaded — site routable at http://${getHostname(slug)}`);
}

/**
 * Applies the k8s manifest then writes the host nginx config.
 * After this returns the site is live on the LAN at <slug>.siteportal.web
 * for any client using this server as DNS.
 */
function applyManifest(slug, imageTag, logger) {
  const manifestPath = path.join(MANIFESTS_DIR, `${slug}.yaml`);

  // ── Kubernetes ──────────────────────────────────────────────────────────────
  logger.step(`Writing Kubernetes manifest → ${manifestPath}`);
  fs.writeFileSync(manifestPath, generateManifest(slug, imageTag), "utf8");

  logger.step(`Applying manifest to cluster...`);
  execSync(`kubectl apply -f ${manifestPath}`, { stdio: "pipe", timeout: 30_000 });
  logger.info(`Manifest applied`);

  logger.step(`Waiting for rollout: site-${slug}...`);
  execSync(
    `kubectl rollout status deployment/site-${slug} --namespace=default --timeout=90s`,
    { stdio: "pipe", timeout: 95_000 }
  );
  logger.info(`Rollout complete`);

  // ── Host nginx ──────────────────────────────────────────────────────────────
  applyNginxConfig(slug, logger);
}

/**
 * Tears down everything for a slug — k8s resources + nginx config.
 */
function deleteDeployment(slug, logger) {
  const manifestPath = path.join(MANIFESTS_DIR, `${slug}.yaml`);
  const nginxConfigPath = path.join(NGINX_SITES_DIR, `${slug}.conf`);

  if (fs.existsSync(manifestPath)) {
    logger.step(`Deleting Kubernetes resources for ${slug}...`);
    execSync(`kubectl delete -f ${manifestPath} --ignore-not-found=true`, {
      stdio: "pipe",
      timeout: 30_000,
    });
    fs.unlinkSync(manifestPath);
    logger.info(`Kubernetes resources deleted`);
  }

  if (fs.existsSync(nginxConfigPath)) {
    logger.step(`Removing nginx config for ${slug}...`);
    fs.unlinkSync(nginxConfigPath);
    execSync("sudo nginx -t && sudo systemctl reload nginx", {
      stdio: "pipe",
      timeout: 10_000,
    });
    logger.info(`Nginx config removed and reloaded`);
  }
}

module.exports = { applyManifest, generateManifest, deleteDeployment, getHostname };